language: php
php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  - composer self-update
  - export BASEDIR=${PWD}

install:
  - phpenv rehash
  - composer install

before_script:
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`
  - ./bin/install_drupal_mysql.sh
  - cd html
  - $BASEDIR/vendor/bin/drush runserver --server=builtin 8080 --strict=0 &
  - sleep 4
  - cd ..
  
script:
  - $BASEDIR/vendor/bin/behat
